FROM node:18-alpine

RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*
RUN npm install -g node-gyp

WORKDIR /app

COPY src /app/src
COPY package.json .
COPY package-lock.json .
COPY .proxyrc .

RUN npm install

CMD ["npm", "start"]
