version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

  # Placed as a separate container because prisma studio and bun container can't play nice
  prisma-studio:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev-prisma-studio
    container_name: prisma-studio
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=${DEV_DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:1234"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DEV_DATABASE_URL}
    volumes:
      - ./backend:/app
      # This volume exists to generate api types for frontend on code changes
      - ./frontend:/frontend
volumes:
  pgdata-dev:
