version: "3"
services:
  # postgres-dev:
  #   image: postgres:15
  #   container_name: postgres-dev
  #   environment:
  #     - POSTGRES_USER=${DEV_POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${DEV_POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata-dev:/var/lib/postgresql/data

  # nextjs-dev:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: nextjs-dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=${DEV_NEXT_PUBLIC_API_URL}
  #   volumes:
  #     - ./frontend:/usr/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:1234"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    expose:
      - "3000:3000"
    # depends_on:
    #   - postgres-dev
    environment:
      - DATABASE_URL=${DEV_DATABASE_URL}
    volumes:
      - ./backend:/app
# volumes:
#   pgdata-dev:
