version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB}
    expose:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:1234"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    expose:
      - "3000:3000"
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DEV_DATABASE_URL}
    volumes:
      - ./backend:/app
volumes:
  pgdata-dev:
