version: "3"
services:
  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   environment:
  #     - POSTGRES_USER=${DEV_POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${DEV_POSTGRES_DB}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
